### ISSUE TITLE
Changing the code in mlp lib doesn't propagate in ipython-analysis

### ISSUE THREAD

**Issue by duchoang** [muvr/muvr-analytics#11]
After initial setup by this script: ./init-env.sh:

1. Open any notebook: ipython-analysis/exercise-mlp.ipynb
2. Modify code in any source mlp/*.py
3. Restart kernel in notebook, but we still don't see any new changes
4. To fix this, need to re-run the script  ./init-env.sh (which may take very long time ~20min to setup)

**Comment by tmbo** [comment]
I added auto reload to the notebooks so a kernel restart is not necessary. I will close this one for now.
